# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Home"
    url: '#about'
    weight: 1

  - name: "About Me"
    url: "about_me/"
    weight: 2

  - name: "Research"
    identifier: research
    url: "/research"
    weight: 3

  - name: "Teaching"
    identifier: teaching
    url: "/teaching"
    weight: 4

  - name: "Resources"
    identifier: resources
    url: "/resources"
    weight: 5
  - name: "Lecturing"
    parent: resources
    url: "/resources/lecturing"
    weight: 1 
  - name: "Coding"
    parent: resources
    url: "/resources/coding"
    weight: 2 
  - name: "Misc"
    parent: resources
    url: "/resources/misc"
    weight: 3  

  - name: "Connect"
    url: "/connect"
    weight: 50

 
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
